"""PDF report generation for valuation reports."""

from datetime import datetime, timezone

from fpdf import FPDF

from app.constants import METHOD_NAMES
from app.models import ValuationReport, ValuationResult


def fmt_currency(value: float) -> str:
    if abs(value) >= 1_000_000_000:
        return f"${value / 1_000_000_000:.1f}B"
    if abs(value) >= 1_000_000:
        return f"${value / 1_000_000:.1f}M"
    if abs(value) >= 1_000:
        return f"${value / 1_000:.0f}K"
    return f"${value:.0f}"


def fmt_percent(value: float) -> str:
    return f"{value * 100:.1f}%"


def _pretty_key(key: str) -> str:
    return key.replace("_", " ").title()


# Explicit formatting hints for assumption keys to avoid magnitude-guessing.
_PERCENT_KEYS = frozenset({
    "growth_rate", "discount_rate", "terminal_growth_rate",
    "profit_margin", "index_return",
})
_CURRENCY_KEYS = frozenset({
    "revenue", "target_revenue", "post_money_valuation",
    "index_at_round", "index_current",
})
_COUNT_KEYS = frozenset({
    "peer_count", "projection_years",
})


def _pretty_value(key: str, value: object) -> str:
    if isinstance(value, (int, float)):
        if key in _PERCENT_KEYS:
            return fmt_percent(float(value))
        if key in _CURRENCY_KEYS:
            return fmt_currency(float(value))
        if key in _COUNT_KEYS:
            return str(int(value))
        if isinstance(value, float) and value != int(value):
            return f"{value:.2f}"
        return str(int(value)) if isinstance(value, float) else str(value)
    return str(value)


class _ReportPDF(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        self.cell(0, 10, f"Generated by VC Audit Tool  |  {ts}  |  Page {self.page_no()}", align="C")


def _add_method_section(pdf: _ReportPDF, result: ValuationResult) -> None:
    # Method header
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(0, 10, METHOD_NAMES.get(result.methodology, result.methodology), new_x="LMARGIN", new_y="NEXT")

    # Value + range
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, f"Estimated Value: {fmt_currency(result.estimated_value)}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0, 7,
        f"Range: {fmt_currency(result.value_range[0])} - {fmt_currency(result.value_range[1])}",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(3)

    # Key Assumptions table
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Key Assumptions", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    col_w = pdf.epw / 2
    for key, value in result.assumptions.items():
        pdf.set_fill_color(245, 245, 245)
        pdf.cell(col_w, 6, f"  {_pretty_key(key)}", border=0, fill=True)
        pdf.cell(col_w, 6, _pretty_value(key, value), border=0, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Audit Trail
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Audit Trail", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    for i, step in enumerate(result.steps, 1):
        pdf.set_font("Helvetica", "B", 10)
        pdf.multi_cell(0, 6, f"{i}. {step.description}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 5, step.detail, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Data Sources
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Data Sources", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    for citation in result.citations:
        pdf.multi_cell(0, 5, f"  - {citation}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)


def generate_report_pdf(report: ValuationReport) -> bytes:
    """Generate a PDF report from a ValuationReport and return raw bytes."""
    pdf = _ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title / header
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(30, 64, 175)
    pdf.cell(0, 12, "Valuation Report", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, f"Company: {report.company_name}", new_x="LMARGIN", new_y="NEXT")
    sector_display = report.sector.replace("_", " ").title()
    pdf.cell(0, 7, f"Sector: {sector_display}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Date: {report.created_at.strftime('%Y-%m-%d %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Report ID: {report.id[:8]}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Summary table (multi-method)
    if len(report.results) > 1:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(30, 64, 175)
        pdf.cell(0, 10, "Summary", new_x="LMARGIN", new_y="NEXT")

        # Table header
        col_widths = [pdf.epw * 0.34, pdf.epw * 0.22, pdf.epw * 0.22, pdf.epw * 0.22]
        headers = ["Method", "Estimated Value", "Range Low", "Range High"]
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(255, 255, 255)
        pdf.set_fill_color(30, 64, 175)
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 7, f" {header}", border=1, fill=True)
        pdf.ln()

        # Table rows
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(0, 0, 0)
        for result in report.results:
            name = METHOD_NAMES.get(result.methodology, result.methodology)
            pdf.set_fill_color(248, 248, 248)
            pdf.cell(col_widths[0], 7, f" {name}", border=1, fill=True)
            pdf.cell(col_widths[1], 7, f" {fmt_currency(result.estimated_value)}", border=1, fill=True)
            pdf.cell(col_widths[2], 7, f" {fmt_currency(result.value_range[0])}", border=1, fill=True)
            pdf.cell(col_widths[3], 7, f" {fmt_currency(result.value_range[1])}", border=1, fill=True)
            pdf.ln()

        # Aggregate row
        values = [r.estimated_value for r in report.results]
        lows = [r.value_range[0] for r in report.results]
        highs = [r.value_range[1] for r in report.results]
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_fill_color(230, 240, 255)
        pdf.cell(col_widths[0], 7, " Mean / Min / Max", border=1, fill=True)
        mean_val = sum(values) / len(values)
        pdf.cell(col_widths[1], 7, f" {fmt_currency(mean_val)}", border=1, fill=True)
        pdf.cell(col_widths[2], 7, f" {fmt_currency(min(lows))}", border=1, fill=True)
        pdf.cell(col_widths[3], 7, f" {fmt_currency(max(highs))}", border=1, fill=True)
        pdf.ln()

        # Convergence callout
        spread = max(values) - min(values)
        avg = mean_val if mean_val != 0 else 1
        pct = spread / avg * 100
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(80, 80, 80)
        if pct < 25:
            pdf.cell(0, 6, f"Methods converge well (spread: {pct:.0f}% of mean).", new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.cell(0, 6, f"Notable divergence across methods (spread: {pct:.0f}% of mean).", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(6)

    # Per-method detail sections
    for result in report.results:
        _add_method_section(pdf, result)

    return bytes(pdf.output())
